from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import darkblue


def generate_pdf_report(
    filename: str,
    vehicle_make: str,
    vehicle_model: str,
    vehicle_year: str,
    symptoms: str,
    diagnosis: str,
    image_analysis: str,
    repair_cost: str,
    maintenance: str
):
    """
    Generate professional PDF diagnostic report.
    """

    document = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER
    title.textColor = darkblue

    heading = styles["Heading2"]

    body = styles["BodyText"]

    story = []

    story.append(
        Paragraph(
            "AI AUTOMOTIVE DIAGNOSTIC REPORT",
            title
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Vehicle Information</b>",
            heading
        )
    )

    story.append(
        Paragraph(
            f"""
Make: {vehicle_make}<br/>
Model: {vehicle_model}<br/>
Year: {vehicle_year}
""",
            body
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            "<b>Customer Symptoms</b>",
            heading
        )
    )

    story.append(
        Paragraph(
            symptoms.replace("\n", "<br/>"),
            body
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            "<b>AI Diagnosis</b>",
            heading
        )
    )

    story.append(
        Paragraph(
            diagnosis.replace("\n", "<br/>"),
            body
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            "<b>Vehicle Damage Analysis</b>",
            heading
        )
    )

    story.append(
        Paragraph(
            image_analysis.replace("\n", "<br/>"),
            body
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            "<b>Estimated Repair Cost</b>",
            heading
        )
    )

    story.append(
        Paragraph(
            repair_cost,
            body
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            "<b>Maintenance Recommendation</b>",
            heading
        )
    )

    story.append(
        Paragraph(
            maintenance.replace("\n", "<br/>"),
            body
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by AI Automotive Diagnostic Assistant",
            body
        )
    )

    document.build(story)